name: CI Pipline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    
    steps:
    
      - name: Checking code
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: if push event
        if: github.event_name == 'push'
        run: echo "Triggered by push"

      - name: if pull_request event 
        if: github.event_name == 'pull_request'
        run: echo "Triggered by pull_request"
      
    
  
      
